image: java:8

before_script:
- chmod +x gradlew
- cp ./src/main/resources/.sample-application.properties ./src/main/resources/application.properties

build:
  stage: build
  script:
  - ./gradlew -g /cache/.gradle clean assemble
  allow_failure: false

test:
  stage: test
  script:
  - ./gradlew -g /cache/.gradle check
